// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_12_FONT_ID (679055512)
#define NOTOSERIF_14_FONT_ID (2930750)
#define NOTOSERIF_16_FONT_ID (267896146)
#define NOTOSERIF_18_FONT_ID (2105911382)
#define NOTOSANS_12_FONT_ID (2130023115)
#define NOTOSANS_14_FONT_ID (-343501334)
#define NOTOSANS_16_FONT_ID (871087166)
#define NOTOSANS_18_FONT_ID (-1291776587)
#define UI_10_FONT_ID (-1301603271)
#define UI_12_FONT_ID (-428789454)
#define SMALL_FONT_ID (-1184514470)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
